# Generated by Django 4.2.6 on 2023-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
