# Generated by Django 4.2.6 on 2023-10-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_book_options_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Без названия', max_length=100, unique=True, verbose_name='Название книги'),
        ),
    ]
